title: <p align="center"> Likhith D Gowda </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="file:///C:/Users/likhi/OneDrive/Desktop/Resume/Likhith_Resume_Updated.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/likhith-gowda-370091180/">LinkedIn</a> |
  <a href="https://github.com/Likhi17">GitHub</a>
  
  <br>   
  Software Engineer with expertise in  Manual/Functional Testing, SQL, Git, Python, Jira, Java(OOPS)  looking for a challenging career opportunity and collaboration in Software development.
  <br>
  </p>



theme: jekyll-theme-minimal
